**FTT**

In [155]:
# All imports
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import string
import uuid
from google.colab import drive
import os

In [156]:
# Mount google drive and provide the read from and write-to folders
drive.mount('/content/drive')
folder_path = '/content/drive/My Drive/example_results/csv_results'

new_folder_path = '/content/drive/My Drive/example_results/json_results'
os.makedirs(new_folder_path, exist_ok=True)

write_folder_path = '/content/drive/My Drive/example_results/json_results'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [157]:
# Function to read a given file from a given folder in CSV format
def read_events(folder_path,file_path,start):
  csv_file_path = os.path.join(folder_path, file_path)
  df = pd.read_csv(csv_file_path)

  # For gid generation
  df['number'] = range(start, start+ len(df))

  # Convert column to datetime type
  df['evt_gmt'] = pd.to_datetime(df['evt_gmt'])

  # Convert datetime column to timestamp
  df['timestamp'] = df['evt_gmt'].apply(lambda x: x.timestamp())
  df['timestamp'] = df['timestamp'].astype(int)

  if 'buyer' in df.columns:
    df['gid_new']= df.apply(lambda row: f"device456@-{row['buyer']}-123-{row['style']}-@-" + f"{row['timestamp']}-{row['number']}", axis=1)
  return df

In [158]:
ftt = read_events(folder_path,'regulated_synthetic_ftt.csv',1)
ftt.head()

,eid,evt_gmt,factory_date,plan_id,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,evn,ftt_count,defective_count,defect_count,reject_count,rectified_count,input_count,rw_defective_count,number,timestamp,gid_new
0,e58d88d3-721c-4613-8e58-fa911fd0b4ae,2024-07-26 02:00:09,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,ftt,1,0,0,0,0,0,0,1,1721959209,device456@-M&S-123-3667M-@-1721959209-1
1,b3397c59-f4cd-43b0-aeaa-e481c9e7709d,2024-07-26 02:00:44,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,ftt,1,0,0,0,0,0,0,2,1721959244,device456@-M&S-123-3667M-@-1721959244-2
2,d426b72e-7772-47c7-948f-8ede30d84379,2024-07-26 02:01:25,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,ftt,1,0,0,0,0,0,0,3,1721959285,device456@-M&S-123-3667M-@-1721959285-3
3,425e0a09-5a31-4c0f-989c-9cb4cbfb1666,2024-07-26 02:01:42,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,ftt,1,0,0,0,0,0,0,4,1721959302,device456@-M&S-123-3667M-@-1721959302-4
4,23a905f8-312f-42be-bae3-b3d7622f01de,2024-07-26 02:01:56,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,XL,ftt,1,0,0,0,0,0,0,5,1721959316,device456@-M&S-123-3667M-@-1721959316-5

In [159]:
pd.set_option('display.max_columns', None)

In [160]:
sample = ftt.head(1)
sample

,eid,evt_gmt,factory_date,plan_id,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,evn,ftt_count,defective_count,defect_count,reject_count,rectified_count,input_count,rw_defective_count,number,timestamp,gid_new
0,e58d88d3-721c-4613-8e58-fa911fd0b4ae,2024-07-26 02:00:09,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,ftt,1,0,0,0,0,0,0,1,1721959209,device456@-M&S-123-3667M-@-1721959209-1

In [161]:
# Function to convert the DataFrame row to the nested JSON structure
def create_nested_json_ftt(row):

  # Define a helper function to replace NaN with empty string
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""


    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "evn": row["evn"],
            "ecv": 1,
            "evl": row["ftt_count"],
            "ety": "count",
            "dod": {
                "sznm": row["size"],
                "szid": str(row["size_id"]),
                "gid": row["gid_new"]
            }
        },
        "where": {
            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])}
            ],
            "pid": row["plan_id"],
            "oid": "order202"
        }
    }
    return json_data

In [162]:
# Apply the function to each row in the DataFrame
ftt_output = ftt.apply(create_nested_json_ftt, axis=1).tolist()
import json
print(json.dumps(ftt_output[0], indent=4))

{
    "eid": "e58d88d3-721c-4613-8e58-fa911fd0b4ae",
    "when": {
        "evt": 1721959209,
        "cit": 1721959209,
        "cot": 1721959209,
        "sid": "1",
        "snm": "Morning"
    },
    "who": {
        "uid": "user123",
        "did": "device456",
        "apt": "endline_qc",
        "buf": "out",
        "hsk": "primary"
    },
    "what": {
        "evn": "ftt",
        "ecv": 1,
        "evl": 1,
        "ety": "count",
        "dod": {
            "sznm": "M",
            "szid": "1",
            "gid": "device456@-M&S-123-3667M-@-1721959209-1"
        }
    },
    "where": {
        "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
        "fid": "ID_PAS",
        "stpv": "1.0.0",
        "lat": "6.6363",
        "lon": "79.9528",
        "org": [
            {
                "k": "tenant",
                "i": "",
                "v": ""
            },
            {
                "k": "cluster",
                "i": "",
                "v": ""
            },
            {
                "k": "factory",
                "i": "ID_PAS",
                "v": "PT.Purnama Asih Sur"
            },
            {
                "k": "department",
                "i": "SW",
                "v": "Sewing"
            },
            {
                "k": "floor",
                "i": "F1",
                "v": "Ground Floor"
            },
            {
                "k": "section",
                "i": "",
                "v": ""
            },
            {
                "k": "line",
                "i": "F1M7",
                "v": "Line 07"
            },
            {
                "k": "station",
                "i": "F1M7ST02",
                "v": "Station 2"
            }
        ]
    },
    "about": {
        "scp": "production",
        "ord": [
            {
                "k": "buyer",
                "i": "1",
                "v": "M&S"
            },
            {
                "k": "po",
                "i": "1",
                "v": "2011242746"
            },
            {
                "k": "style",
                "i": "1",
                "v": "3667M"
            }
        ],
        "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
        "oid": "order202"
    }
}

In [163]:
# Write the json to a drive location
ftt_path = os.path.join(write_folder_path, 'ftt.json')
with open(ftt_path, 'w') as f:
    json.dump(ftt_output, f, indent=4)

**Reject with Reasons**

In [164]:
# Read reject reasons
reject_r = read_events(folder_path,'regulated_synthetic_rr.csv',1)
reject_r.head(1)

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_id,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,sign,gid,reject_reason_id,reject_reason_code,reject_reason,number,timestamp,gid_new
0,ef1bb22f-7a9c-4a62-9fe9-9fb68f130aac,2024-07-26 02:31:27,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,XL,1,DS2F3LWW,5,304,Fabric Defect,1,1721961087,device456@-M&S-123-3667M-@-1721961087-1

In [165]:
# Read reject counts
reject_count = read_events(folder_path,'regulated_synthetic_reject.csv',1)
reject_count.head(1)

,eid,evt_gmt,factory_date,plan_id,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,gid,evn,ftt_count,defective_count,defect_count,reject_count,rectified_count,input_count,rw_defective_count,number,timestamp,gid_new
0,ef1bb22f-7a9c-4a62-9fe9-9fb68f130aac,2024-07-26 02:31:27,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,XL,DS2F3LWW,reject,0,0,0,1,0,0,0,1,1721961087,device456@-M&S-123-3667M-@-1721961087-1

In [166]:
# Merge to findout plan+id for reject reasons
reject = pd.merge(reject_r, reject_count[['plan_id', 'eid']], on='eid')
reject

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_id,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,sign,gid,reject_reason_id,reject_reason_code,reject_reason,number,timestamp,gid_new,plan_id
0,ef1bb22f-7a9c-4a62-9fe9-9fb68f130aac,2024-07-26 02:31:27,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,XL,1,DS2F3LWW,5,304,Fabric Defect,1,1721961087,device456@-M&S-123-3667M-@-1721961087-1,12f0ffe7-c509-49b5-b203-83be908b2881
1,b11002f4-ab78-4bbe-bf44-fe88e588dcbe,2024-07-26 03:49:10,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,1,4XF0M58S,5,304,Fabric Defect,2,1721965750,device456@-M&S-123-3667M-@-1721965750-2,12f0ffe7-c509-49b5-b203-83be908b2881
2,cb2b535f-5044-4a68-8342-240436524985,2024-07-26 03:58:59,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,1,491Z91HM,2,301,Uneven,3,1721966339,device456@-M&S-123-3667M-@-1721966339-3,12f0ffe7-c509-49b5-b203-83be908b2881
3,1742c50b-3092-4d43-aeb2-cfd52c25eab1,2024-07-26 04:02:44,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,1,6ZG8LKAD,4,303,Needle Defect,4,1721966564,device456@-M&S-123-3667M-@-1721966564-4,12f0ffe7-c509-49b5-b203-83be908b2881
4,55c2bc65-b69f-46d7-9f88-09948ab1136d,2024-07-26 05:10:21,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,1,5UCWMPVI,9,308,Other,5,1721970621,device456@-M&S-123-3667M-@-1721970621-5,12f0ffe7-c509-49b5-b203-83be908b2881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,2fc546dc-5d89-4d6d-b70d-79c7e89968a1,2024-08-01 10:28:15,2024-08-01,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M8,Line 08,F1M8ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M8-F1M8ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,1,C9WG31KW,8,307,Material Mistake,292,1722508095,device456@-M&S-123-3667M-@-1722508095-292,13f0ffe7-c509-49b5-b203-83be908b2887
292,ee772919-fd18-4a4e-ab31-3c8b02fb4806,2024-08-01 11:36:36,2024-08-01,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M8,Line 08,F1M8ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M8-F1M8ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,M,1,YBICHSEH,3,302,Puckering,293,1722512196,device456@-M&S-123-3667M-@-1722512196-293,13f0ffe7-c509-49b5-b203-83be908b2887
293,744a4191-0329-40d1-9693-e80c833f041d,2024-08-01 11:49:35,2024-08-01,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M8,Line 08,F1M8ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M8-F1M8ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,XL,1,OU2TDNE9,8,307,Material Mistake,294,1722512975,device456@-M&S-123-3667M-@-1722512975-294,13f0ffe7-c509-49b5-b203-83be908b2887
294,a7473456-5a06-4af1-be44-96532f902136,2024-08-01 12:35:04,2024-08-01,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M8,Line 08,F1M8ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M8-F1M8ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,1,BARS3F8K,8,307,Material Mistake,295,1722515704,device456@-M&S-123-3667M-@-1722515704-295,13f0ffe7-c509-49b5-b203-83be908b2887
295,c9617d0e-6026-400c-aacb-d58324adfc29,2024-08-01 13:20:16,2024-08-01,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M8,Line 08,F1M8ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M8-F1M8ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,1,V2WIJBER,6,305,Shading,296,1722518416,device456@-M&S-123-3667M-@-1722518416-296,13f0ffe7-c509-49b5-b203-83be908b2887

In [167]:
# Function to create the nested JSON

def create_nested_json_reject(row):

    # Helper function to handle NaN values
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""

    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "evn": "reject",
            "ecv": 1,
            "evl": 1,
            "ety": "count",
            "dod": {
                "sznm": row["size"],
                "szid": str(row["size_id"]),
                "reject": [
                    {
                        "rri": str(row["reject_reason_id"]),
                        "rrc": str(row["reject_reason_code"]),
                        "rrn": row["reject_reason"]
                    }
                ],
                "gid": row["gid"]
            }
        },
        "where": {
            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
                 ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])}
                ],
            "pid": row["plan_id"],
            "oid": "order202"
        }
    }
    return json_data

In [168]:
# Apply the function to each row in the DataFrame
reject_output = reject.apply(create_nested_json_reject, axis=1).tolist()
print(json.dumps(reject_output[0], indent=4))

{
    "eid": "ef1bb22f-7a9c-4a62-9fe9-9fb68f130aac",
    "when": {
        "evt": 1721961087,
        "cit": 1721961087,
        "cot": 1721961087,
        "sid": "1",
        "snm": "Morning"
    },
    "who": {
        "uid": "user123",
        "did": "device456",
        "apt": "endline_qc",
        "buf": "out",
        "hsk": "primary"
    },
    "what": {
        "evn": "reject",
        "ecv": 1,
        "evl": 1,
        "ety": "count",
        "dod": {
            "sznm": "XL",
            "szid": "1",
            "reject": [
                {
                    "rri": "5",
                    "rrc": "304",
                    "rrn": "Fabric Defect"
                }
            ],
            "gid": "DS2F3LWW"
        }
    },
    "where": {
        "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
        "fid": "ID_PAS",
        "stpv": "1.0.0",
        "lat": "6.6363",
        "lon": "79.9528",
        "org": [
            {
                "k": "tenant",
                "i": "",
                "v": ""
            },
            {
                "k": "cluster",
                "i": "",
                "v": ""
            },
            {
                "k": "factory",
                "i": "ID_PAS",
                "v": "PT.Purnama Asih Sur"
            },
            {
                "k": "department",
                "i": "SW",
                "v": "Sewing"
            },
            {
                "k": "floor",
                "i": "F1",
                "v": "Ground Floor"
            },
            {
                "k": "section",
                "i": "",
                "v": ""
            },
            {
                "k": "line",
                "i": "F1M7",
                "v": "Line 07"
            },
            {
                "k": "station",
                "i": "F1M7ST02",
                "v": "Station 2"
            }
        ]
    },
    "about": {
        "scp": "production",
        "ord": [
            {
                "k": "buyer",
                "i": "1",
                "v": "M&S"
            },
            {
                "k": "po",
                "i": "1",
                "v": "2011242746"
            },
            {
                "k": "style",
                "i": "1",
                "v": "3667M"
            }
        ],
        "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
        "oid": "order202"
    }
}

In [169]:
# Write the json to a drive location
reject_path = os.path.join(write_folder_path, 'reject.json')
with open(reject_path, 'w') as f:
    json.dump(reject_output, f, indent=4)

**Defectives and Defects**

In [170]:
# Read defective
defective = read_events(folder_path,'regulated_synthetic_defective.csv',1)
defective.head(1)

,eid,evt_gmt,factory_date,plan_id,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,evn,gid,ftt_count,defective_count,defect_count,reject_count,rectified_count,input_count,rw_defective_count,unit_id,unit,number,timestamp,gid_new
0,a6f20839-e969-4738-8484-2eede1ac3198,2024-07-26 02:08:59,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,defective,JEZ5XL6F,0,1,1,0,0,0,0,NaN,NaN,1,1721959739,device456@-M&S-123-3667M-@-1721959739-1

In [171]:
# Read defect
defect = read_events(folder_path,'regulated_synthetic_defect.csv',1)
defect.head(1)

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,stp,size,hsk,buf,apt,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,sign,gid,issue_id,issue_code,issue_color_code,issue,operation_id,operation_code,operation,image,silhouette_id,silhouette,x,y,number,timestamp,gid_new
0,f3f26679-ab26-40f7-902c-4da973aa4b59,2024-07-26 02:08:59,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,NaN,NaN,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,L,primary,out,endline_qc,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,1,JEZ5XL6F,24,SQD24,#CCCCFF,Join Stc,11,110,Att Elastic at Both Legs,front,1,shirt_style1,0.98,0.35,1,1721959739,device456@-M&S-123-3667M-@-1721959739-1

In [172]:
# Function to create the nested JSON
def create_nested_json_defective(row, defect):

    # Helper function to handle NaN values
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""

    # Filter defects for the current gid
    current_defects = defect[defect['gid'] == row['gid']]
    current_defects.rename(columns={'issue_id': "iid",'issue_code': "icd",
                                'issue_color_code': "icc",'issue': "inm",
                                'operation_id': "opi",'operation_code': "ocd",
                                'operation': "onm",'image': "img",'silhouette_id': "sli",'silhouette': "sln",
                                }, inplace=True)
    current_defects['iid'] = current_defects['iid'].astype(str)
    current_defects['opi'] = current_defects['opi'].astype(str)
    current_defects['ocd'] = current_defects['ocd'].astype(str)
    current_defects['sli'] = current_defects['sli'].astype(str)

    current_defects = current_defects[["iid","icd", "inm","icc","opi","ocd","onm","sli","sln","img","x","y"]]
    current_defects = current_defects.to_dict(orient='records')

    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "evn": "defective",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "sznm": row["size"],
                "szid": str(row["size_id"]),
                "defective": current_defects,
                "gid": row["gid"],
                "dtl": "123"
            }
        },
        "where": {
            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
     "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
                 ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])}
               ],
            "pid": row["plan_id"],
            "oid": "order202"
        }
    }
    return json_data

In [173]:
# Apply the function to each row in the defective DataFrame
json_defective = defective.apply(lambda row: create_nested_json_defective(row, defect), axis=1).tolist()

print(json.dumps(json_defective[8:10], indent=4))

[
    {
        "eid": "2e91355e-f666-4a1d-8130-dbe0fd26fa25",
        "when": {
            "evt": 1721965110,
            "cit": 1721965110,
            "cot": 1721965110,
            "sid": "1",
            "snm": "Morning"
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": "endline_qc",
            "buf": "out",
            "hsk": "primary"
        },
        "what": {
            "evn": "defective",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "sznm": "M",
                "szid": "1",
                "defective": [
                    {
                        "iid": "12",
                        "icd": "SQD12",
                        "inm": "Steps",
                        "icc": "#808000",
                        "opi": "18",
                        "ocd": "117",
                        "onm": "Att Match Bow at Waist",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "back",
                        "x": 0.83,
                        "y": 0.38
                    }
                ],
                "gid": "1GGF59MO",
                "dtl": "123"
            }
        },
        "where": {
            "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
            "fid": "ID_PAS",
            "stpv": "1.0.0",
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {
                    "k": "tenant",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "cluster",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "factory",
                    "i": "ID_PAS",
                    "v": "PT.Purnama Asih Sur"
                },
                {
                    "k": "department",
                    "i": "SW",
                    "v": "Sewing"
                },
                {
                    "k": "floor",
                    "i": "F1",
                    "v": "Ground Floor"
                },
                {
                    "k": "section",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "line",
                    "i": "F1M7",
                    "v": "Line 07"
                },
                {
                    "k": "station",
                    "i": "F1M7ST02",
                    "v": "Station 2"
                }
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {
                    "k": "buyer",
                    "i": "1",
                    "v": "M&S"
                },
                {
                    "k": "po",
                    "i": "1",
                    "v": "2011242746"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "3667M"
                }
            ],
            "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
            "oid": "order202"
        }
    },
    {
        "eid": "2492b0b1-dbdd-410b-b2bd-7b2fe9a3be86",
        "when": {
            "evt": 1721966889,
            "cit": 1721966889,
            "cot": 1721966889,
            "sid": "1",
            "snm": "Morning"
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": "endline_qc",
            "buf": "out",
            "hsk": "primary"
        },
        "what": {
            "evn": "defective",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "sznm": "XL",
                "szid": "1",
                "defective": [
                    {
                        "iid": "20",
                        "icd": "SQD20",
                        "inm": "Up Down",
                        "icc": "#CCFFFF",
                        "opi": "17",
                        "ocd": "116",
                        "onm": "Att Bow at CF Waist W / mark",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "front",
                        "x": 1.0,
                        "y": 0.31
                    }
                ],
                "gid": "IVS5XFZS",
                "dtl": "123"
            }
        },
        "where": {
            "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
            "fid": "ID_PAS",
            "stpv": "1.0.0",
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {
                    "k": "tenant",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "cluster",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "factory",
                    "i": "ID_PAS",
                    "v": "PT.Purnama Asih Sur"
                },
                {
                    "k": "department",
                    "i": "SW",
                    "v": "Sewing"
                },
                {
                    "k": "floor",
                    "i": "F1",
                    "v": "Ground Floor"
                },
                {
                    "k": "section",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "line",
                    "i": "F1M7",
                    "v": "Line 07"
                },
                {
                    "k": "station",
                    "i": "F1M7ST02",
                    "v": "Station 2"
                }
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {
                    "k": "buyer",
                    "i": "1",
                    "v": "M&S"
                },
                {
                    "k": "po",
                    "i": "1",
                    "v": "2011242746"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "3667M"
                }
            ],
            "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
            "oid": "order202"
        }
    }
]

In [174]:
# Write the json to a drive location
defective_path = os.path.join(write_folder_path, 'defective.json')
with open(defective_path, 'w') as f:
    json.dump(json_defective, f, indent=4)

**RECTIFIED**

In [175]:
# Read rectified
rectified = read_events(folder_path,'regulated_synthetic_rectified.csv',1)
rectified.head(1)

,eid,evt_gmt,factory_date,plan_id,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,size_id,size,evn,gid,ftt_count,defective_count,defect_count,reject_count,rectified_count,input_count,rw_defective_count,number,timestamp,gid_new
0,141e3822-9dd7-45b6-996b-860d38fa53fa,2024-07-26 02:09:04,2024-07-26,12f0ffe7-c509-49b5-b203-83be908b2881,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,1,L,rectified,JEZ5XL6F,0,0,0,0,1,0,0,1,1721959744,device456@-M&S-123-3667M-@-1721959744-1

In [176]:
# Function to create the nested JSON
def create_nested_json_rectified(row, defect):

    # Helper function to handle NaN values
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""

    # Filter defects for the current gid
    current_defects = defect[defect['gid'] == row['gid']]
    current_defects.rename(columns={'issue_id': "iid",'issue_code': "icd",
                                'issue_color_code': "icc",'issue': "inm",
                                'operation_id': "opi",'operation_code': "ocd",
                                'operation': "onm",'image': "img",'silhouette_id': "sli",'silhouette': "sln",
                                }, inplace=True)
    current_defects['iid'] = current_defects['iid'].astype(str)
    current_defects['opi'] = current_defects['opi'].astype(str)
    current_defects['ocd'] = current_defects['ocd'].astype(str)
    current_defects['sli'] = current_defects['sli'].astype(str)

    current_defects = current_defects[["iid","icd", "inm","icc","opi","ocd","onm","sli","sln","img","x","y"]]
    current_defects = current_defects.to_dict(orient='records')

    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "evn": "rectified",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "gid": row["gid"],
                "dtl": "123",
                "rectified": current_defects ,
                "sznm": row["size"],
                "szid": str(row["size_id"])

            }
        },
        "where": {
            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
     "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
                 ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])}
               ],
            "pid": row["plan_id"],
            "oid": "order202"
        }
    }
    return json_data

In [177]:
# Apply the function to each row in the rectified DataFrame
json_rectified = rectified.apply(lambda row: create_nested_json_rectified(row, defect), axis=1).tolist()

print(json.dumps(json_rectified[4:6], indent=4))

[
    {
        "eid": "503c0057-6c5e-4c6a-8faf-95b7c43aeb3d",
        "when": {
            "evt": 1721963407,
            "cit": 1721963407,
            "cot": 1721963407,
            "sid": "1",
            "snm": "Morning"
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": "endline_qc",
            "buf": "out",
            "hsk": "primary"
        },
        "what": {
            "evn": "rectified",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "gid": "JNCXPEMX",
                "dtl": "123",
                "rectified": [
                    {
                        "iid": "13",
                        "icd": "SQD13",
                        "inm": "Wavy",
                        "icc": "#800080",
                        "opi": "10",
                        "ocd": "109",
                        "onm": "Join Bk Gusset Seam",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "back",
                        "x": 0.45,
                        "y": 0.2
                    }
                ],
                "sznm": "XL",
                "szid": "1"
            }
        },
        "where": {
            "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
            "fid": "ID_PAS",
            "stpv": "1.0.0",
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {
                    "k": "tenant",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "cluster",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "factory",
                    "i": "ID_PAS",
                    "v": "PT.Purnama Asih Sur"
                },
                {
                    "k": "department",
                    "i": "SW",
                    "v": "Sewing"
                },
                {
                    "k": "floor",
                    "i": "F1",
                    "v": "Ground Floor"
                },
                {
                    "k": "section",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "line",
                    "i": "F1M7",
                    "v": "Line 07"
                },
                {
                    "k": "station",
                    "i": "F1M7ST02",
                    "v": "Station 2"
                }
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {
                    "k": "buyer",
                    "i": "1",
                    "v": "M&S"
                },
                {
                    "k": "po",
                    "i": "1",
                    "v": "2011242746"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "3667M"
                }
            ],
            "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
            "oid": "order202"
        }
    },
    {
        "eid": "5f6162ff-deb6-4a89-bc8a-fe9edde43cf7",
        "when": {
            "evt": 1721965016,
            "cit": 1721965016,
            "cot": 1721965016,
            "sid": "1",
            "snm": "Morning"
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": "endline_qc",
            "buf": "out",
            "hsk": "primary"
        },
        "what": {
            "evn": "rectified",
            "ecv": 1,
            "evl": 1,
            "ety": "category",
            "dod": {
                "gid": "HZQI9DTZ",
                "dtl": "123",
                "rectified": [
                    {
                        "iid": "30",
                        "icd": "SQD30",
                        "inm": "Lace Defect",
                        "icc": "#800000",
                        "opi": "13",
                        "ocd": "112",
                        "onm": "Tack & Att label at CB Waist",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "back",
                        "x": 1.0,
                        "y": 0.73
                    },
                    {
                        "iid": "14",
                        "icd": "SQD14",
                        "inm": "Bartack",
                        "icc": "#008080",
                        "opi": "1",
                        "ocd": "100",
                        "onm": "Join Fnt Gusset Seam",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "front",
                        "x": 0.69,
                        "y": 0.13
                    },
                    {
                        "iid": "2",
                        "icd": "SQD2",
                        "inm": "Long Ends",
                        "icc": "#FFFFFF",
                        "opi": "14",
                        "ocd": "113",
                        "onm": "Att FO Elastic Around Waist",
                        "sli": "1",
                        "sln": "shirt_style1",
                        "img": "back",
                        "x": 0.63,
                        "y": 0.02
                    }
                ],
                "sznm": "XL",
                "szid": "1"
            }
        },
        "where": {
            "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
            "fid": "ID_PAS",
            "stpv": "1.0.0",
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {
                    "k": "tenant",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "cluster",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "factory",
                    "i": "ID_PAS",
                    "v": "PT.Purnama Asih Sur"
                },
                {
                    "k": "department",
                    "i": "SW",
                    "v": "Sewing"
                },
                {
                    "k": "floor",
                    "i": "F1",
                    "v": "Ground Floor"
                },
                {
                    "k": "section",
                    "i": "",
                    "v": ""
                },
                {
                    "k": "line",
                    "i": "F1M7",
                    "v": "Line 07"
                },
                {
                    "k": "station",
                    "i": "F1M7ST02",
                    "v": "Station 2"
                }
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {
                    "k": "buyer",
                    "i": "1",
                    "v": "M&S"
                },
                {
                    "k": "po",
                    "i": "1",
                    "v": "2011242746"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "3667M"
                }
            ],
            "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
            "oid": "order202"
        }
    }
]

In [178]:
# Write the json to a drive location
rectified_path = os.path.join(write_folder_path, 'rectified.json')
with open(rectified_path, 'w') as f:
    json.dump(json_rectified, f, indent=4)

**MANPOWER**

In [179]:
# Read manpower
manpower = read_events(folder_path,'regulated_synthetic_manpower.csv',1)
manpower.head(1)

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,manpower,operator,helper,ironman,qc,number,timestamp
0,7064f04e-e5ea-487c-9c87-f4ffe1a82cb2,2024-07-26 02:00:00,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,28,23,5,0,0,1,1721959200

In [180]:
import pandas as pd

def create_nested_json_from_manpower(row):
    # Helper function to handle NaN values
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""

    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "evn": "manpower_change",
            "ecv": 1,
            "evl": 1,
            "ety": "change",
            "dod": {
                "mpc": [
                    {"k":"operator", "v": row["operator"]},
                    {"k":"helper", "v": row["helper"]},
                    {"k":"ironman", "v": row["ironman"]},
                    {"k":"qc", "v": row["qc"]}

                ]
            }
        },
        "where": {

            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
                 ]
      },
        "about": {
            "scp": "production"
        }
    }
    return json_data

In [181]:
# Apply the function to each row in the rectified DataFrame
json_manpower = manpower.apply(lambda row: create_nested_json_from_manpower(row), axis=1).tolist()

print(json.dumps(json_manpower[4], indent=4))

{
    "eid": "e8b4e513-045d-4a65-b984-5f428c024606",
    "when": {
        "evt": 1721973600,
        "cit": 1721973600,
        "cot": 1721973600,
        "sid": "1",
        "snm": "Morning"
    },
    "who": {
        "uid": "user123",
        "did": "device456",
        "apt": "endline_qc",
        "buf": "out",
        "hsk": "primary"
    },
    "what": {
        "evn": "manpower_change",
        "ecv": 1,
        "evl": 1,
        "ety": "change",
        "dod": {
            "mpc": [
                {
                    "k": "operator",
                    "v": 23
                },
                {
                    "k": "helper",
                    "v": 5
                },
                {
                    "k": "ironman",
                    "v": 0
                },
                {
                    "k": "qc",
                    "v": 0
                }
            ]
        }
    },
    "where": {
        "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
        "fid": "ID_PAS",
        "stpv": "1.0.0",
        "lat": "6.6363",
        "lon": "79.9528",
        "org": [
            {
                "k": "tenant",
                "i": "",
                "v": ""
            },
            {
                "k": "cluster",
                "i": "",
                "v": ""
            },
            {
                "k": "factory",
                "i": "ID_PAS",
                "v": "PT.Purnama Asih Sur"
            },
            {
                "k": "department",
                "i": "SW",
                "v": "Sewing"
            },
            {
                "k": "floor",
                "i": "F1",
                "v": "Ground Floor"
            },
            {
                "k": "section",
                "i": "",
                "v": ""
            },
            {
                "k": "line",
                "i": "F1M7",
                "v": "Line 07"
            },
            {
                "k": "station",
                "i": "F1M7ST02",
                "v": "Station 2"
            }
        ]
    },
    "about": {
        "scp": "production"
    }
}

In [182]:
# Write the json to a drive location
manpower_path = os.path.join(write_folder_path, 'manpower.json')
with open(manpower_path, 'w') as f:
    json.dump(json_manpower, f, indent=4)

**RUNNING ORDER CHANGE**

In [183]:
# Read manpower
manpower = read_events(folder_path,'regulated_synthetic_manpower.csv',1)
manpower.head(1)

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,manpower,operator,helper,ironman,qc,number,timestamp
0,7064f04e-e5ea-487c-9c87-f4ffe1a82cb2,2024-07-26 02:00:00,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,28,23,5,0,0,1,1721959200

In [184]:
bctx_temp = manpower.copy()

# Convert factort_date to a datetime for a plan merge
bctx_temp['factory_date'] = pd.to_datetime(bctx_temp['factory_date'])

In [185]:
plan_path = os.path.join(folder_path, 'plan.csv')
plan = pd.read_csv(plan_path)
plan.head(1)

,plan_id,plan_type,created_ts,modified_ts,date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,stp,buyer_id,buyer,vendor_id,vendor,po_id,po,so_id,so,li_id,li,fabric_type_id,fabric_type,product_category_id,product_category,product_type_id,product_type,style_id,style,color_id,color,qty,mins,operator,helper,ironman,qc,manpower,smv,produced_mins
0,12f0ffe7-c509-49b5-b203-83be908b2881,2,2024-07-26 10:00:00,2024-07-26 14:00:00,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,ID_PAS-SW-BD1-F1-F1M7,1,M&S,NaN,NaN,1,2011242746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Top,1,3667M,1,Print,2112,660,23,5,0,0,28,8.28,17487.36

In [186]:
# Convert 'date' column in 'plan' DataFrame to datetime
plan['date'] = pd.to_datetime(plan['date'])

In [187]:
# Merge plan and change dataframes on plan date and get the bctx in the required
# nested format
synthetic_bctx= pd.merge(bctx_temp, plan[['plan_id','date','module_id','buyer','buyer_id', 'po', 'po_id', 'style', 'style_id',
                                                    'color', 'color_id']], how='left',
                         left_on=['factory_date', 'module_id'], right_on=['date','module_id'])
synthetic_bctx['change_type'] = 'running_order'
synthetic_bctx['scope'] = 'application'
synthetic_bctx['factory_date'] = synthetic_bctx['factory_date'].dt.date
synthetic_bctx['timestamp'] = synthetic_bctx['evt_gmt'].apply(lambda x: x.timestamp())
synthetic_bctx['timestamp'] = synthetic_bctx['timestamp'].astype(int)
synthetic_bctx.head(1)

,eid,evt_gmt,factory_date,shift_id,shift,tenant_id,tenant,cluster_id,cluster,factory_id,factory,building_id,building,unit_id,unit,department_id,department,floor_id,floor,zone_id,zone,section_id,section,module_id,module,station_id,station,hsk,buf,apt,stp,stpv,manpower,operator,helper,ironman,qc,number,timestamp,plan_id,date,buyer,buyer_id,po,po_id,style,style_id,color,color_id,change_type,scope
0,7064f04e-e5ea-487c-9c87-f4ffe1a82cb2,2024-07-26 02:00:00,2024-07-26,1,Morning,NaN,NaN,NaN,NaN,ID_PAS,PT.Purnama Asih Sur,BD1,Building 01,NaN,NaN,SW,Sewing,F1,Ground Floor,NaN,NaN,NaN,NaN,F1M7,Line 07,F1M7ST02,Station 2,primary,out,endline_qc,ID_PAS-SW-BD1-F1-F1M7-F1M7ST02,1.0.0,28,23,5,0,0,1,1721959200,12f0ffe7-c509-49b5-b203-83be908b2881,2024-07-26,M&S,1,2011242746,1,3667M,1,Print,1,running_order,application

In [188]:
# Function to convert the DataFrame row to the nested JSON structure
def create_nested_json_running_order_change(row):

  # Define a helper function to replace NaN with empty string
    def handle_nan(value):
        return str(value) if pd.notna(value) else ""


    json_data = {
        "eid": row["eid"],
        "when": {
            "evt": row["timestamp"],
            "cit": row["timestamp"],
            "cot": row["timestamp"],
            "sid": str(row["shift_id"]),
            "snm": row["shift"]
        },
        "who": {
            "uid": "user123",
            "did": "device456",
            "apt": row["apt"],
            "buf": row["buf"],
            "hsk": row["hsk"]
        },
        "what": {
            "ecv": 1,
            "ety": "change",
            "evl": 1,
            "evn": "running_order_change",
            "dod": {
                "roc":
                  [
                    {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                    {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                    {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])},
                    {"k": "style", "i":str( row["color_id"]), "v": str(row["color"])}
                 ]
            }
        },
        "where": {
            "stp": row["stp"],
            "fid": str(row["factory_id"]),
            "stpv": str(row["stpv"]),
            "lat": "6.6363",
            "lon": "79.9528",
            "org": [
                {"k": "tenant", "i": handle_nan(row["tenant_id"]), "v": handle_nan(row["tenant"])},
                {"k":"cluster" , "i": handle_nan(row["cluster_id"]), "v": handle_nan(row["cluster"])},
                {"k": "factory", "i": handle_nan(row["factory_id"]), "v": handle_nan(row["factory"])},
                {"k": "department", "i": handle_nan(row["department_id"]), "v": handle_nan(row["department"])},
                {"k": "floor", "i": handle_nan(row["floor_id"]), "v": handle_nan(row["floor"])},
                {"k":"section" , "i": handle_nan(row["section_id"]), "v": handle_nan(row["section"])},
                {"k": "line", "i": handle_nan(row["module_id"]), "v": handle_nan(row["module"])},
                {"k": "station", "i": handle_nan(row["station_id"]), "v": handle_nan(row["station"])}
            ]
        },
        "about": {
            "scp": "production",
            "ord": [
                {"k": "buyer", "i": str(row["buyer_id"]), "v": str(row["buyer"])},
                {"k": "po", "i": str(row["po_id"]), "v": str(row["po"])},
                {"k": "style", "i":str( row["style_id"]), "v": str(row["style"])}
            ],
            "pid": row["plan_id"],
            "oid": "order202"
        }
    }
    return json_data

In [189]:
# Apply the function to each row in the synthetic_bctx
json_running_order_change = synthetic_bctx.apply(lambda row: create_nested_json_running_order_change(row), axis=1).tolist()

print(json.dumps(json_running_order_change[4], indent=4))

{
    "eid": "e8b4e513-045d-4a65-b984-5f428c024606",
    "when": {
        "evt": 1721973600,
        "cit": 1721973600,
        "cot": 1721973600,
        "sid": "1",
        "snm": "Morning"
    },
    "who": {
        "uid": "user123",
        "did": "device456",
        "apt": "endline_qc",
        "buf": "out",
        "hsk": "primary"
    },
    "what": {
        "ecv": 1,
        "ety": "change",
        "evl": 1,
        "evn": "running_order_change",
        "dod": {
            "roc": [
                {
                    "k": "buyer",
                    "i": "1",
                    "v": "M&S"
                },
                {
                    "k": "po",
                    "i": "1",
                    "v": "2011242746"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "3667M"
                },
                {
                    "k": "style",
                    "i": "1",
                    "v": "Print"
                }
            ]
        }
    },
    "where": {
        "stp": "ID_PAS-SW-BD1-F1-F1M7-F1M7ST02",
        "fid": "ID_PAS",
        "stpv": "1.0.0",
        "lat": "6.6363",
        "lon": "79.9528",
        "org": [
            {
                "k": "tenant",
                "i": "",
                "v": ""
            },
            {
                "k": "cluster",
                "i": "",
                "v": ""
            },
            {
                "k": "factory",
                "i": "ID_PAS",
                "v": "PT.Purnama Asih Sur"
            },
            {
                "k": "department",
                "i": "SW",
                "v": "Sewing"
            },
            {
                "k": "floor",
                "i": "F1",
                "v": "Ground Floor"
            },
            {
                "k": "section",
                "i": "",
                "v": ""
            },
            {
                "k": "line",
                "i": "F1M7",
                "v": "Line 07"
            },
            {
                "k": "station",
                "i": "F1M7ST02",
                "v": "Station 2"
            }
        ]
    },
    "about": {
        "scp": "production",
        "ord": [
            {
                "k": "buyer",
                "i": "1",
                "v": "M&S"
            },
            {
                "k": "po",
                "i": "1",
                "v": "2011242746"
            },
            {
                "k": "style",
                "i": "1",
                "v": "3667M"
            }
        ],
        "pid": "12f0ffe7-c509-49b5-b203-83be908b2881",
        "oid": "order202"
    }
}

In [190]:
# Write the json to a drive location
running_order_change_path = os.path.join(write_folder_path, 'running_order_change.json')
with open(running_order_change_path, 'w') as f:
    json.dump(json_running_order_change, f, indent=4)

**COMBINED JSON**

In [191]:
# Combine all lists of json events to one list
combined_list = [item for sublist in [ftt_output, reject_output, json_defective, json_rectified,json_manpower, json_running_order_change] for item in sublist]
print(combined_list[-1])

{'eid': '97c17c9d-e4a0-4a40-8595-f08481b117a6', 'when': {'evt': 1722515400, 'cit': 1722515400, 'cot': 1722515400, 'sid': '1', 'snm': 'Morning'}, 'who': {'uid': 'user123', 'did': 'device456', 'apt': 'endline_qc', 'buf': 'out', 'hsk': 'primary'}, 'what': {'ecv': 1, 'ety': 'change', 'evl': 1, 'evn': 'running_order_change', 'dod': {'roc': [{'k': 'buyer', 'i': '1', 'v': 'M&S'}, {'k': 'po', 'i': '1', 'v': '2011242746'}, {'k': 'style', 'i': '1', 'v': '3667M'}, {'k': 'style', 'i': '1', 'v': 'Print'}]}}, 'where': {'stp': 'ID_PAS-SW-BD1-F1-F1M8-F1M8ST02', 'fid': 'ID_PAS', 'stpv': '1.0.0', 'lat': '6.6363', 'lon': '79.9528', 'org': [{'k': 'tenant', 'i': '', 'v': ''}, {'k': 'cluster', 'i': '', 'v': ''}, {'k': 'factory', 'i': 'ID_PAS', 'v': 'PT.Purnama Asih Sur'}, {'k': 'department', 'i': 'SW', 'v': 'Sewing'}, {'k': 'floor', 'i': 'F1', 'v': 'Ground Floor'}, {'k': 'section', 'i': '', 'v': ''}, {'k': 'line', 'i': 'F1M8', 'v': 'Line 08'}, {'k': 'station', 'i': 'F1M8ST02', 'v': 'Station 2'}]}, 'about': {'scp': 'production', 'ord': [{'k': 'buyer', 'i': '1', 'v': 'M&S'}, {'k': 'po', 'i': '1', 'v': '2011242746'}, {'k': 'style', 'i': '1', 'v': '3667M'}], 'pid': '13f0ffe7-c509-49b5-b203-83be908b2887', 'oid': 'order202'}}

In [192]:
# Write the json to a drive location
all_events_path = os.path.join(write_folder_path, 'all_events.json')
with open(all_events_path, 'w') as f:
    json.dump(combined_list, f, indent=4)